[features]
seeds = false
skip-lint = false
[programs.localnet]
sol_message = "ubTav1er9CLME873MRCT63gw6gcH882hbc2AGaRTHD2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/bhaskarkh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
